### ISSUE TITLE
Error with updated pandas version

### ISSUE THREAD

**Issue by anlo328** [baudisgroup/mecan4cna#1]
Dear Baudis group,

Today, I came back to using mecan4cna after some time. Using the same scripts that used to work for me, I got a terminating error

`drop() takes from 1 to 2 positional arguments but 3 were given`

Pretty sure this has to do with some recent update with how pandas works. I reverted my version to `pandas==1.5.3`, and the same scripts were working again. However, I get the warning:

```
FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_models = df_models.drop(['base', 'thresh','index'],1)
```

Hope this note can help you fix what's probably a small issue

Best wishes,
Andi

**Comment by KyleGao** [comment]
Dear Andi,

Thank you for pointing out the problem and suggesting a solution! I actually never expected basic functions such drop() would have an argument change. Anyway, I have added the required versions of each package so the program won't break because of the package updates. The downside is you will probably have to use it in a separate virtual environment.

Best,
Bo
